name: My Name
description: Description
body:
- type: textarea
  attributes:
    label: Which?
    description: Enter ID(s) here
    placeholder: |
      Name #1 | 101
      Name #2 | 102
- type: checkboxes
  attributes:
    label: Which should apply?
    description: |
      Description: foobar
    options:
      - label: AAA
        required: false
      - label: BBBB
        required: false
      - label: CCCC
        required: false
      - label: EEEE
        required: false
- type: textarea
  attributes:
    label: ATC Instructions
    description: Instructions for the developer for handling this issue. **Please do not change**
    value: |

      See this [runbook entry][runbook_legacy]. For everything else, see [runbook entry][runbook].

      /cc @MitMaro

      If you have any questions feel free to reach out in the [#channel][runbook] channel on Slack.

      [board]: https://github.com/orgs/1
      [runbook]: https://github.com/orgs/2
      [runbook_legacy]: https://github.com/orgs/3
        
