name: Release Latest

on:
    push:
        branches:
            - master
jobs:
  update-latest-tag:
    runs-on: ubuntu-latest
    name: Update Latest Tag
    env:
      TARGET_RELEASE_ID: 113191004
      GITHUB_ACCESS_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      REPOSITORY: "MitMaro/test"
      DEFAULT_BRANCH: "master"
    steps:
      - uses: actions/checkout@v3
      - name: "Update Tag and Title"
        run: "./.github/scripts/update-tag.bash"

  debian:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    needs: update-latest-tag
    timeout-minutes: 10
    container:
      image: 'docker://debian:sid-slim'
    steps:
      - uses: actions/checkout@v3
      - name: "System Setup"
        run: |
          apt-get update;
          apt-get --assume-yes -f install curl build-essential pkg-config;
        env:
          DEBIAN_FRONTEND: noninteractive
          TZ: "America/St_Johns"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: "Build"
        run: |
          cargo build --release
          cp target/release/interactive-rebase-tool target/release/debian-interactive-rebase-tool
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          allowUpdates: true
          artifacts: "target/release/debian-interactive-rebase-tool"
          artifactContentType: "application/vnd.debian.binary-package"
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          makeLatest: false
          prerelease: true
          updateOnlyUnreleased: true
  ubuntu:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    needs: update-latest-tag
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: "Build"
        run: |
          cargo build --release
          cp target/release/interactive-rebase-tool target/release/ubuntu-interactive-rebase-tool
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          allowUpdates: true
          artifacts: "target/release/ubuntu-interactive-rebase-tool"
          artifactContentType: "application/vnd.debian.binary-package"
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          makeLatest: false
          prerelease: true
          updateOnlyUnreleased: true
  macos-x86:
    name: MacOS x86 Latest
    runs-on: macos-latest
    timeout-minutes: 10
    needs: update-latest-tag
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
      - name: "Build"
        run: |
          cargo build --release
          cp target/release/interactive-rebase-tool target/release/macos-x86-interactive-rebase-tool
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          allowUpdates: true
          artifacts: "target/release/macos-x86-interactive-rebase-tool"
          artifactContentType: "application/x-mach-binary"
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          makeLatest: false
          prerelease: true
          updateOnlyUnreleased: true

  macos-arm:
    name: MacOS ARM Latest
    runs-on: macos-latest
    timeout-minutes: 10
    needs: update-latest-tag
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          targets: aarch64-apple-darwin
      - name: "Build"
        run: |
          cargo build --release
          cp target/release/interactive-rebase-tool target/release/macos-arm-interactive-rebase-tool
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          allowUpdates: true
          artifacts: "target/release/macos-arm-interactive-rebase-tool"
          artifactContentType: "application/x-mach-binary"
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          makeLatest: false
          prerelease: true
          updateOnlyUnreleased: true

  windows:
    name: Windows Latest
    runs-on: windows-latest
    timeout-minutes: 10
    needs: update-latest-tag
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: "Build"
        run: "cargo rustc --target x86_64-pc-windows-msvc --release --bin interactive-rebase-tool"
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          allowUpdates: true
          artifacts: "target/x86_64-pc-windows-msvc/release/interactive-rebase-tool.exe"
          artifactContentType: "application/x-mach-binary"
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          makeLatest: false
          prerelease: true
          updateOnlyUnreleased: true

  alpine:
    name: Alpine Latest
    runs-on: ubuntu-latest
    needs: update-latest-tag
    container:
      image: 'docker://rust:alpine'
    steps:
      - uses: actions/checkout@v3
      - run: |
          apk update
          apk upgrade
          apk add bash
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: "Build"
        run: |
          cargo build --release
          cp target/release/interactive-rebase-tool target/release/alpine-interactive-rebase-tool
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          allowUpdates: true
          artifacts: "target/release/alpine-interactive-rebase-tool"
          artifactContentType: "application/vnd.debian.binary-package"
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          makeLatest: false
          prerelease: true
          updateOnlyUnreleased: true
  arch:
    name: Arch Latest
    runs-on: ubuntu-latest
    needs: update-latest-tag
    container:
      image: 'docker://archlinux:base-devel'
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: "Build"
        run: |
          cargo build --release
          cp target/release/interactive-rebase-tool target/release/arch-interactive-rebase-tool
      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          allowUpdates: true
          artifacts: "target/release/arch-interactive-rebase-tool"
          artifactContentType: "application/vnd.debian.binary-package"
          replacesArtifacts: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          makeLatest: false
          prerelease: true
          updateOnlyUnreleased: true